
obstacle_range: 10.0
raytrace_range: 10.0
robot_radius: 0.3
inflation_radius: 0.5
transform_tolerance: 1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
