### To be used with the rest-client extension of vscode

### Create Robot 1
POST http://localhost:8080/db/robots HTTP/1.1
content-type: application/json

{
  "name": "Robot1",
  "platform": {
      "OS": "Ubuntu 16.04",
      "ROS": "Kinetic",
      "CPU": "Cortex-A57 MPCore",
      "GPU": "Nvidia Pascal",
      "Batteries": "40000 mAh",
      "Frame": "turtlebot"
  }
}

### Create Robot 2
POST http://localhost:8080/db/robots HTTP/1.1
content-type: application/json

{
  "name": "Robot2",
  "platform": {
      "OS": "Ubuntu 18.04",
      "ROS": "Melodic",
      "CPU": "Cortex-A57 MPCore",
      "GPU": "Nvidia Pascal",
      "Batteries": "40000 mAh",
      "Frame": "pioneer"
  }
}

### Get Robots
GET http://localhost:8080/db/robots


###
@robot1 = 5dc59e1db7217d0014134503
@robot2  = 5dc59f3eb7217d0014134504

### Patrols

POST http://localhost:8080/db/robots/{{robot1}}/patrols
content-type: application/json

{
  "name": "Patrol 1",
  "description_text": "huHFHOIHGL;HKL;HGLASHGLKHGLha;HOIHGIORHGIOERHGAHWE;GHWO",
  "last_modified": "2019-11-07T06:52:19.831Z",
  "waypoints": [
    {"coordinate" : {"x": 15, "y": 20, "yaw": 15}, "hold_time_s": 10 },
    {"coordinate" : {"x": 50, "y": 70, "yaw": 65}, "hold_time_s": 10 },
    {"coordinate" : {"x": 65, "y": 100, "yaw": 92}, "hold_time_s": 10 }
  ]
}

POST http://localhost:8080/db/robots/{{robot1}}/patrols
content-type: application/json

{
  "name": "Patrol 2",
  "description_text": "huHFHOIHGL;HKL;HGLASHGLKHGLha;HOIHGIORHGIOERHGAHWE;GHWO",
  "last_modified": "2019-11-07T06:52:19.831Z",
  "waypoints": [
    {"coordinate" : {"x": 15, "y": 20, "yaw": 15}, "hold_time_s": 25 },
    {"coordinate" : {"x": 50, "y": 70, "yaw": 65}, "hold_time_s": 25 },
    {"coordinate" : {"x": 65, "y": 100, "yaw": 92}, "hold_time_s": 25 }
  ]
}

POST http://localhost:8080/db/robots/{{robot2}}/patrols
content-type: application/json

{
  "name": "Patrol A",
  "description_text": "huHFHOIHGL;HKL;HGLASHGLKHGLha;HOIHGIORHGIOERHGAHWE;GHWO",
  "last_modified": "2019-11-07T06:52:19.831Z",
  "waypoints": [
    {"coordinate" : {"x": 15, "y": 20, "yaw": 15}, "hold_time_s": 0 },
    {"coordinate" : {"x": 50, "y": 70, "yaw": 67}, "hold_time_s": 0 },
    {"coordinate" : {"x": 65, "y": 100, "yaw": 10}, "hold_time_s": 0 }
  ]
}

GET http://localhost:8080/db/robots/{{robot1}}/patrols

### Create events for the first robot
POST http://localhost:8080/db/robots/{{robot1}}/events
content-type: application/json

{
    "object": "Event 1",
    "description_text": "asdasdadsa",
    "context": "night",
    "time": "2019-11-07T06:52:19.831Z",
    "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
    "tags": ["red"],
    "alert": false,
    "viewed": false
}

###
POST http://localhost:8080/db/robots/{{robot1}}/events
content-type: application/json

{
    "object": "Event 2",
    "description_text": "asdasdadsa",
    "context": "night",
    "time": "2019-11-01T06:52:19.831Z",
    "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
    "tags": ["blue"],
    "alert": false,
    "viewed": false
}

###
POST http://localhost:8080/db/robots/{{robot1}}/events
content-type: application/json

{
    "object": "Event 3",
    "description_text": "asdasdadsa",
    "context": "night",
    "time": "2019-11-04T06:52:19.831Z",
    "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
    "tags": ["yellow"],
    "alert": false,
    "viewed": false
}

###
POST http://localhost:8080/db/robots/{{robot1}}/events
content-type: application/json

{
  "object": "Event 4",
  "description_text": "asdasdadsa",
  "context": "night",
  "time": "2019-11-04T06:52:19.831Z",
  "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
  "tags": ["green"],
  "alert": false,
  "viewed": false
}

###
POST http://localhost:8080/db/robots/{{robot1}}/events
content-type: application/json

{
    "object": "Event 5",
    "description_text": "asdasdadsa",
    "context": "night",
    "time": "2019-10-23T00:00:00.999Z",
    "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
    "tags": ["a"],
    "alert": false,
    "viewed": false
}

### Get robot 1 event
GET http://localhost:8080/db/robots/{{robot1}}/events


### Create events for the second robot
POST http://localhost:8080/db/robots/{{robot2}}/events
content-type: application/json

{
    "object": "Event 10",
    "description_text": "asdasdadsa",
    "context": "night",
    "time": "2019-11-07T06:52:19.831Z",
    "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
    "tags": ["red"],
    "alert": false,
    "viewed": false
}

###
POST http://localhost:8080/db/robots/{{robot2}}/events
content-type: application/json

{
  "robot": "{{robot2}}",
  "object": "Event 11",
  "description_text": "asdasdadsa",
  "context": "night",
  "time": "2019-11-01T06:52:19.831Z",
  "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
  "tags": ["b"],
  "alert": false,
  "viewed": false
}

###
POST http://localhost:8080/db/robots/{{robot2}}/events
content-type: application/json

{
    "object": "Event 12",
    "description_text": "asdasdadsa",
    "context": "night",
    "time": "2019-10-23T00:00:00.999Z",
    "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
    "tags": ["c"],
    "alert": false,
    "viewed": false
}

###
POST http://localhost:8080/db/robots/{{robot2}}/events
content-type: application/json

{
    "object": "Event 12",
    "description_text": "asdasdadsa",
    "context": "night",
    "time": "2018-10-23T00:00:00.999Z",
    "location_coordinate": {"x": 15, "y": 20, "yaw": 15},
    "tags": ["c"],
    "alert": false,
    "viewed": false
}

### Get robot 2 events
GET http://localhost:8080/db/robots/{{robot2}}/events

### Get last 30 days events for robot 1
GET http://localhost:8080/db/robots/{{robot1}}/events
content-type: application/json

{
  "after": "2019-10-11T22:04:07.921Z",
  "before": "2019-11-08T22:04:07.921Z",
  "search_expression": "",
  "alert": false,
  "viewed": false
}

### Get last 30 days events for robot 2
GET http://localhost:8080/db/robots/{{robot2}}/events
content-type: application/json

{
  "after": "2019-10-11T22:04:07.921Z",
  "before": "2019-11-08T22:04:07.921Z",
  "search_expression": "",
  "alert": false,
  "viewed": false
}