#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# make all scripts executable
chmod -R +x $DIR

# add scripts to path
export PATH="$PATH:$DIR"
echo "$DIR added to \$PATH"

