set(_CATKIN_CURRENT_PACKAGE "securbot_hbba_cfg")
set(securbot_hbba_cfg_VERSION "0.0.0")
set(securbot_hbba_cfg_MAINTAINER "alex <alex@todo.todo>")
set(securbot_hbba_cfg_PACKAGE_FORMAT "2")
set(securbot_hbba_cfg_BUILD_DEPENDS "hbba_synth")
set(securbot_hbba_cfg_BUILD_EXPORT_DEPENDS "hbba_synth")
set(securbot_hbba_cfg_BUILDTOOL_DEPENDS "catkin")
set(securbot_hbba_cfg_BUILDTOOL_EXPORT_DEPENDS )
set(securbot_hbba_cfg_EXEC_DEPENDS "hbba_synth")
set(securbot_hbba_cfg_RUN_DEPENDS "hbba_synth")
set(securbot_hbba_cfg_TEST_DEPENDS )
set(securbot_hbba_cfg_DOC_DEPENDS )
set(securbot_hbba_cfg_URL_WEBSITE "")
set(securbot_hbba_cfg_URL_BUGTRACKER "")
set(securbot_hbba_cfg_URL_REPOSITORY "")
set(securbot_hbba_cfg_DEPRECATED "")